name: Test on PR

on:
  pull_request:
    branchs: [master]

jobs:
  test:
    name: Test infra on PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: IaC Apply
        env:
          COMMAND_IAC: terraform
        run: |
          cd infra
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan



